=== matishpatil/GenAI_Data_Engineering/JSON Schema/mock_json_schema2.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": [
    "id",
    "first_name",
    "last_name", 
    "email",
    "favorite_color",
    "ip_address"
  ],
  "properties": {
    "id": {
      "type": "integer"
    },
    "first_name": {
      "type": "string"
    },
    "last_name": {
     "type": "string"
    },
    "email": {
      "type": "string",
      "format": "email"
    },
    "favorite_color": {
      "type": "string"
    },
    "ip_address": {
      "type": "string",
      "format": "ipv4"
    }
  },
  "additionalProperties": false
}

=== matishpatil/GenAI_Data_Engineering/JSON Schema/mock_data.json
[{"id":1,"first_name":"Hedvig","last_name":"Ryding","email":"hryding0@dedecms.com","favorite_color":"Yellow","ip_address":"244.26.34.24"},
{"id":2,"first_name":"Dalt","last_name":"Aynold","email":"daynold1@google.it","favorite_color":"Purple","ip_address":"42.133.113.165"},
{"id":3,"first_name":"Vallie","last_name":"Hurkett","email":"vhurkett2@comcast.net","favorite_color":"Maroon","ip_address":"123.90.138.183"},
{"id":4,"first_name":"Mordecai","last_name":"Casserley","email":"mcasserley3@ucoz.com","favorite_color":"Crimson","ip_address":"147.92.201.113"},
{"id":5,"first_name":"Drucy","last_name":"Duffrie","email":"dduffrie4@accuweather.com","favorite_color":"Maroon","ip_address":"198.85.178.16"},
{"id":6,"first_name":"Katy","last_name":"Longshaw","email":"klongshaw5@edublogs.org","favorite_color":"Purple","ip_address":"105.93.110.181"},
{"id":7,"first_name":"Alethea","last_name":"Gercken","email":"agercken6@yahoo.com","favorite_color":"Mauv","ip_address":"81.61.200.226"},
{"id":8,"first_name":"Iona","last_name":"Milbourne","email":"imilbourne7@paginegialle.it","favorite_color":"Aquamarine","ip_address":"6.10.89.22"},
{"id":9,"first_name":"Melany","last_name":"Kirton","email":"mkirton8@netlog.com","favorite_color":"Fuscia","ip_address":"172.26.33.201"},
{"id":10,"first_name":"Nicola","last_name":"Guidera","email":"nguidera9@jalbum.net","favorite_color":"Indigo","ip_address":"124.205.222.200"},
{"id":11,"first_name":"Gabrielle","last_name":"Matussevich","email":"gmatussevicha@zimbio.com","favorite_color":"Pink","ip_address":"45.29.40.13"},
{"id":12,"first_name":"Auria","last_name":"MacWilliam","email":"amacwilliamb@opera.com","favorite_color":"Maroon","ip_address":"77.180.58.90"},
{"id":13,"first_name":"Jillayne","last_name":"Bilbrook","email":"jbilbrookc@wp.com","favorite_color":"Blue","ip_address":"114.14.156.8"},
{"id":14,"first_name":"Loutitia","last_name":"Mollatt","email":"lmollattd@ibm.com","favorite_color":"Teal","ip_address":"2.7.227.100"},
{"id":15,"first_name":"John","last_name":"Orcott","email":"jorcotte@lulu.com","favorite_color":"Yellow","ip_address":"167.241.163.249"},
{"id":16,"first_name":"Kizzie","last_name":"Jime","email":"kjimef@creativecommons.org","favorite_color":"Turquoise","ip_address":"103.174.73.46"},
{"id":17,"first_name":"Theobald","last_name":"Gadsby","email":"tgadsbyg@yellowbook.com","favorite_color":"Turquoise","ip_address":null},
{"id":18,"first_name":"Storm","last_name":"Pallent","email":"spallenth@myspace.com","favorite_color":"Pink","ip_address":"28.25.211.209"},
{"id":19,"first_name":"Hadria","last_name":"Tonge","email":"htongei@psu.edu","favorite_color":"Puce","ip_address":"41.4.31.212"},
{"id":20,"first_name":"Kaleena","last_name":"Shalcros","email":"kshalcrosj@mediafire.com","favorite_color":"Goldenrod","ip_address":"172.31.36.208"},
{"id":21,"first_name":"Eddy","last_name":"McAster","email":"emcasterk@usa.gov","favorite_color":"Aquamarine","ip_address":"62.181.165.184"},
{"id":22,"first_name":"Luce","last_name":"Auguste","email":"laugustel@plala.or.jp","favorite_color":"Teal","ip_address":"133.18.192.65"},
{"id":23,"first_name":"Juieta","last_name":"Harnor","email":"jharnorm@mail.ru","favorite_color":"Mauv","ip_address":"162.26.227.57"},
{"id":24,"first_name":"Ricki","last_name":"Mattaus","email":"rmattausn@google.com.br","favorite_color":"Pink","ip_address":"39.133.226.204"},
{"id":25,"first_name":"Naomi","last_name":"Humbles","email":"nhumbleso@unc.edu","favorite_color":"Turquoise","ip_address":"66.121.49.116"},
{"id":26,"first_name":"Alanah","last_name":"Drivers","email":"adriversp@rambler.ru","favorite_color":"Maroon","ip_address":"149.201.183.35"},
{"id":27,"first_name":"Eward","last_name":"Whitehouse","email":"ewhitehouseq@rakuten.co.jp","favorite_color":"Puce","ip_address":"119.186.133.227"},
{"id":28,"first_name":"Betteann","last_name":"Place","email":"bplacer@shutterfly.com","favorite_color":"Goldenrod","ip_address":"70.82.133.162"},
{"id":29,"first_name":"Debora","last_name":"Jezard","email":"djezards@upenn.edu","favorite_color":"Teal","ip_address":"226.110.222.235"},
{"id":30,"first_name":"Mag","last_name":"Oattes","email":"moattest@yolasite.com","favorite_color":"Maroon","ip_address":"48.217.164.168"},
{"id":31,"first_name":"Ruggiero","last_name":"Godspeede","email":"rgodspeedeu@facebook.com","favorite_color":"Khaki","ip_address":"230.129.83.228"},
{"id":32,"first_name":"Filmore","last_name":"Tindall","email":"ftindallv@photobucket.com","favorite_color":"Turquoise","ip_address":"111.3.8.199"},
{"id":33,"first_name":"Pierce","last_name":"Held","email":"pheldw@diigo.com","favorite_color":"Orange","ip_address":"116.251.141.158"},
{"id":34,"first_name":"Osbourn","last_name":"Dunston","email":"odunstonx@sciencedirect.com","favorite_color":"Maroon","ip_address":"82.100.59.197"},
{"id":35,"first_name":"Colby","last_name":"Gaspar","email":"cgaspary@nba.com","favorite_color":"Puce","ip_address":"246.44.216.28"},
{"id":36,"first_name":"Brittni","last_name":"Feasley","email":"bfeasleyz@google.co.uk","favorite_color":"Blue","ip_address":"248.104.112.141"},
{"id":37,"first_name":"Aldrich","last_name":"Tale","email":"atale10@ask.com","favorite_color":"Yellow","ip_address":"153.93.139.86"},
{"id":38,"first_name":"Darius","last_name":"DeSousa","email":"ddesousa11@vimeo.com","favorite_color":"Pink","ip_address":"120.101.66.14"},
{"id":39,"first_name":"Ansell","last_name":"Wilman","email":"awilman12@dion.ne.jp","favorite_color":"Puce","ip_address":"87.245.176.212"},
{"id":40,"first_name":"Nata","last_name":"Bagshaw","email":"nbagshaw13@qq.com","favorite_color":"Khaki","ip_address":"205.58.154.41"},
{"id":41,"first_name":"Merline","last_name":"MacClenan","email":"mmacclenan14@businessweek.com","favorite_color":"Teal","ip_address":"127.74.228.236"},
{"id":42,"first_name":"Cami","last_name":"Worge","email":"cworge15@gizmodo.com","favorite_color":"Blue","ip_address":"127.91.117.222"},
{"id":43,"first_name":"Jodie","last_name":"Tomaini","email":"jtomaini16@etsy.com","favorite_color":"Teal","ip_address":"179.126.47.162"},
{"id":44,"first_name":"Brandi","last_name":"Gasticke","email":"bgasticke17@etsy.com","favorite_color":"Puce","ip_address":"132.138.81.163"},
{"id":45,"first_name":"Sayre","last_name":"Bampforth","email":"sbampforth18@topsy.com","favorite_color":"Goldenrod","ip_address":"114.11.234.8"},
{"id":46,"first_name":"Adrianna","last_name":"Brailey","email":"abrailey19@army.mil","favorite_color":"Crimson","ip_address":"39.127.239.87"},
{"id":47,"first_name":"Valentine","last_name":"McCrackem","email":"vmccrackem1a@hostgator.com","favorite_color":"Orange","ip_address":"227.242.250.165"},
{"id":48,"first_name":"Claudio","last_name":"Oselton","email":"coselton1b@comcast.net","favorite_color":"Indigo","ip_address":"143.165.233.97"},
{"id":49,"first_name":"Garold","last_name":"Conichie","email":"gconichie1c@xing.com","favorite_color":"Violet","ip_address":"206.92.87.151"},
{"id":50,"first_name":"Nevile","last_name":"Stait","email":"nstait1d@princeton.edu","favorite_color":"Puce","ip_address":"187.166.171.134"},
{"id":51,"first_name":"Granger","last_name":"Gooding","email":"ggooding1e@alibaba.com","favorite_color":"Indigo","ip_address":"120.101.26.80"},
{"id":52,"first_name":"Ewan","last_name":"Astill","email":"eastill1f@state.gov","favorite_color":"Maroon","ip_address":"6.192.178.208"},
{"id":53,"first_name":"Waylen","last_name":"Druhan","email":"wdruhan1g@google.co.uk","favorite_color":"Yellow","ip_address":"234.101.139.40"},
{"id":54,"first_name":"Madelon","last_name":"Brettle","email":"mbrettle1h@twitpic.com","favorite_color":"Puce","ip_address":"12.1.11.141"},
{"id":55,"first_name":"William","last_name":"Wederell","email":"wwederell1i@free.fr","favorite_color":"Puce","ip_address":"5.202.161.109"},
{"id":56,"first_name":"Allan","last_name":"Choak","email":"achoak1j@printfriendly.com","favorite_color":"Aquamarine","ip_address":"217.127.126.29"},
{"id":57,"first_name":"Amy","last_name":"Weymouth","email":"aweymouth1k@bloglines.com","favorite_color":"Mauv","ip_address":"181.139.129.196"},
{"id":58,"first_name":"Connor","last_name":"Eatttok","email":"ceatttok1l@marketwatch.com","favorite_color":"Purple","ip_address":"157.70.199.234"},
{"id":59,"first_name":"Darrick","last_name":"Finder","email":"dfinder1m@washingtonpost.com","favorite_color":"Violet","ip_address":"100.172.112.251"},
{"id":60,"first_name":"Barbe","last_name":"Brixham","email":"bbrixham1n@huffingtonpost.com","favorite_color":"Khaki","ip_address":"55.244.84.240"},
{"id":61,"first_name":"Kaia","last_name":"Flann","email":"kflann1o@twitpic.com","favorite_color":"Puce","ip_address":"79.197.27.45"},
{"id":62,"first_name":"Mordy","last_name":"Randle","email":"mrandle1p@dedecms.com","favorite_color":"Violet","ip_address":"18.87.89.60"},
{"id":63,"first_name":"Graehme","last_name":"Schirach","email":"gschirach1q@harvard.edu","favorite_color":"Violet","ip_address":"60.90.77.59"},
{"id":64,"first_name":"Leroi","last_name":"McKernan","email":"lmckernan1r@ebay.co.uk","favorite_color":"Puce","ip_address":"243.145.241.111"},
{"id":65,"first_name":"Nonna","last_name":"De Bischof","email":"ndebischof1s@businessinsider.com","favorite_color":"Puce","ip_address":"133.10.164.12"},
{"id":66,"first_name":"Dredi","last_name":"Woolner","email":"dwoolner1t@si.edu","favorite_color":"Pink","ip_address":"186.178.124.224"},
{"id":67,"first_name":"Paloma","last_name":"Borit","email":"pborit1u@amazon.com","favorite_color":"Turquoise","ip_address":"4.29.43.150"},
{"id":68,"first_name":"Leonelle","last_name":"Westell","email":"lwestell1v@amazon.de","favorite_color":"Pink","ip_address":"90.61.191.186"},
{"id":69,"first_name":"Kathie","last_name":"Westwick","email":"kwestwick1w@deviantart.com","favorite_color":"Indigo","ip_address":"97.223.73.113"},
{"id":70,"first_name":"Riobard","last_name":"Smoote","email":"rsmoote1x@delicious.com","favorite_color":"Orange","ip_address":"243.231.225.194"},
